### ISSUE TITLE
Other language implementations?

### ISSUE THREAD

**Issue by STBoyden** [EntireTwix/CodeChallenges#2]
Would other language examples be accepted? Then the source for each language can be placed into their own folders within the respective challenge folder.

For example:

```
Root
|_ Sudoku
|____ C++
|____ Rust
|____ Go
|
|_ 15 Challenge
|____ C++
|____ Rust
|____ Go
```

If so, I'll provide Rust examples.

**Comment by EntireTwix** [comment]
I think that would be a good idea, yes. The sudoku example was supposed to be a c++ equivalent (and I'm sure it will be after I fix it), if u wanna make a rust equivalent then ask synergy for the py code. As for the sudoku folder, u can submit your sudoku rust solution whenever u want and I'll add it

**Comment by STBoyden** [comment]
Would you want just the source files or the Cargo project as a whole?

**Comment by EntireTwix** [comment]
cargo project is preferable
